baseURL: https://okw-y.github.io
languageCode: en-EN
title: OKwy
theme: PaperModX

params:
    env: production
    title: "OKwy - Home"
    description: "About"
    author:

    defaultTheme: auto

    assets: 
        favicon: "favicon.ico"

    mainSections:
        - posts

    profileMode:
        enabled: false

    socialIcons:
        - name: github
          url: "https://github.com/okw-y"
        - name: Telegram
          url: "https://t.me/okw_y"

    homeInfoParams:
        Title: "Hello!"
        Content: |
          My name is OKwy. I am a python programmer with two years of experience. 
          Below you can familiarize yourself with my projects.

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        lineNos: false
        noClasses: false
